### PR TITLE
Deprecate all uses of our old randomness services.

### PR DESCRIPTION
**Pull request by mikaelfrykholm**

### CODE REVIEW

**Comment by btmattsson** [comment]
Är vi säkra på att gamla Ubuntu burkar inte behöver pollinate ?

**Comment by mikaelfrykholm** [comment]
Kanske @mariahaider kan gräva nån nån riktigt gammal ubuntu vi kan testa på? Alla som kör Debian är det redan testat på. ubuntu >= 22.04 också via swamid.

**Comment by eest** [comment]
Since the cron job is left behind, wont this trigger alerts when the binary is no longer present?

**Comment by mikaelfrykholm** [comment]
Good catch. Fixed.

**Comment by eest** [comment]
Removing the entry will stop it from being created, but it will not remove it from host that already have it. There will instead be an orphaned cron entry still trying to run. I think to remove it you will need to set it as ensure => absent, see https://www.puppet.com/docs/puppet/5.5/types/cron.html#cron-attribute-ensure

**Comment by mikaelfrykholm** [comment]
Fixed!

**Review by theseal — APPROVED** [review]
LGTM

**Comment by mariahaider** [comment]
We still have some some servers running 18, for example - ipam.sunet.se ( no plan to upgrade, needs to be replaced), ni.sunet.se and other NI servers ( will be upgraded)

**Comment by mariahaider** [comment]
But they all run old 'sunet' branch of course.

**Pull request merged**
