### PR TITLE
puppet lint - on everything

### PR DESCRIPTION
**Pull request by mickenordin**
This is formatting + puppet-lint testing for pull requests and push to testing

### CODE REVIEW

**Review by theseal — APPROVED** [review]
Yes!

**Comment by mickenordin** [comment]
I got all warnings to go away, but I would appreciate many eyes on this.

**Review by eest — APPROVED** [review]
Does not seem to break `run-cosmos -v` on cnaas test machines (norpan). Also tested on knubbis-ops where test machine has been modified to track testing like cnaas-ops already did.

LGTM

**Review by theseal — APPROVED** [review]
Don't have anything in testing but I have fate in your tests.

**Pull request merged**
