### PR TITLE
Some NRPE checks will get fishy results when using a PrivateTmp.

### PR DESCRIPTION
**Pull request by theseal**
E.g check_apt: https://askubuntu.com/questions/1415415/check-apt-issue-with-nagios

### CODE REVIEW

**Comment by theseal** [comment]
Not tested on a new machine.

**Comment by mariahaider** [comment]
Looks good to me but should it apply only to servers running 22.04?

**Review by mickenordin — APPROVED** [review]
Looks good!

**Comment by theseal** [comment]
> Looks good to me but should it apply only to servers running 22.04?

It's needed for Debian aswell.

**Pull request merged**
