### PR TITLE
Monitor expiration of GPG keys

### PR DESCRIPTION
**Pull request by theseal**
Both for cosmos and metadata repo's.

### CODE REVIEW

**Review by mikaelfrykholm — APPROVED** [review]
LGTM. 
Some small nitpicks.
* Maybe set -euo also 
* My backup key is not parsed. It seems to assume only one pub key in each file.

**Comment by theseal** [comment]
Will look in to the other `set`s

Why do you have multiple keys? Tested this in multiple repos and the few files with multiple public keys where a misstake.

**Comment by mikaelfrykholm** [comment]
My backup key uses the same email address as my primary one and when I exported that one it tagged along. I kind of like only having one file for primary and backup key.

**Review by mickenordin — APPROVED** [review]
I think this makes a lot of sense. I also think one key per file, makes sense too, since it makes it easy to spot mistakes, where someone added more than the intended key. It is not that hard to maintain one file per key you need.

**Pull request merged**
