### PR TITLE
Randomize requests to acme-c.sunet.se

### PR DESCRIPTION
**Pull request by mariahaider**
Randomize the minute for sending request to acme-c.sunet.se by servers which run the puppet class with `single_domain: false`

### CODE REVIEW

**Comment by eest** [comment]
I am not sure this works as expected. If `fqdn_rand()` returns "1" this will lead to the minute entry `*/1` which means "run every minute". I am not sure how the rest of the cron entry looks but if all other fields are `*`, would it be enough to run once an hour instead of every 20 minutes? If that is the case then we can probably replace `"*/${minute_random}"` with `"${minute_random}"` which then will mean "run at this minute (every hour)", and then no matter what rand returns the frequency will be the same, just distributed over the full hour.

**Comment by eest** [comment]
Looking at https://www.puppet.com/docs/puppet/5.5/function.html#fqdn_rand it looks like it is exclusive:

> Generates a random Integer number greater than or equal to 0 and less than MAX

... so using `60` is probably correct.

**Comment by mariahaider** [comment]
> ... and if we where to change it to `"${minute_random}"`, keep in mind that the valid range of the minute interval is `0-59`, so in that case we might need to change the value in `fqdn_rand(60)` (I dont recall if the rand range is inclusive (0-60) or exclusive (0-59) of the given number).

Good point, fixed it, running once an hour should be fine.

**Review by eest — APPROVED** [review]
LGTM

**Pull request merged**
